### ISSUE TITLE
Error opencv

### ISSUE THREAD

**Issue by soheer** [gmat/goproMax-ffmpeg-v5#1]
Hello,

we've downloaded opencv4 (version 4.5.5) from source and we want to build ffmpeg package with opencv using this configuration (+ transform 360 package to transform 360 videos [https://github.com/facebook/transform360]):

> ./configure --prefix=/usr/local/transform/ffmpeg --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-version3 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzvbi --enable-avfilter --enable-libmodplug --enable-postproc --enable-pthreads --enable-gpl --disable-debug --disable-stripping --enable-nonfree  --enable-libfdk-aac --enable-libopencv --extra-libs='-lTransform360 -lstdc++' --extra-ldflags=-L/usr/local/lib

but we have error :
ERROR: opencv not found using pkg-config
even though when running pkg-config --modversion opencv4 we got the opencv version

what should we do to solve this problem?

Thanks.

**Comment by gmat** [comment]
opencv install issue not the best place to find help.
Why do you install opencv includes just like they suggest ? `sudo apt-get install libopencv-dev`

You can also try some of the advice from this issue 
https://github.com/facebook/transform360/issues/56
especially this : 
https://github.com/facebook/transform360/issues/56#issuecomment-412466165

Maybe this version (v5) of ffmpeg isn't the appropriated one of this filter (transform360), the last commit are older than 9 months ago. You can test but I won't be surprise if you'll encounter errors after solve this lib dependency error...
Go to the v4 ffmpeg version of this work is the best option to start with.

**Comment by gmat** [comment]
@soheer please if you find a solution close this ticket and better put a feedback. It'll be helpful for people search with similar error.
thks.
