### ISSUE TITLE
Help with compilation

### ISSUE THREAD

**Issue by darrylyong** [gmat/goproMax-ffmpeg-v5#2]
Sorry for what I think is a newbie question.

I am having trouble compiling this project using WSL for a win64 build.  

```
In file included from libavfilter/opencl.h:31,
                 from libavfilter/opencl.c:26:
./libavutil/hwcontext_opencl.h:25:10: fatal error: CL/cl.h: No such file or directory
   25 | #include <CL/cl.h>
      |          ^~~~~~~~~
compilation terminated.
CC      libavfilter/vf_bilateral.o
make: *** [ffbuild/common.mak:78: libavfilter/opencl.o] Error 1
```

How can I fix this error?

(I am using [https://github.com/rdp/ffmpeg-windows-build-helpers.git](https://github.com/rdp/ffmpeg-windows-build-helpers.git), but edited `quick_cross_compile_ffmpeg_fdk_aac_and_x264_using_packaged_mingw64.sh` so that it pulls from this repo instead.)

**Comment by gmat** [comment]
the opencv library's headers are missing. I'm not use to WSL but default it's ubuntu as linux distribution, so open a terminal and execute `sudo apt install libopencv-core-dev`
Maybe you should check this documentation for the setup of your development https://docs.microsoft.com/en-us/windows/wsl/setup/environment

**Comment by darrylyong** [comment]
Thanks. It was installed, but I think the issue is that I'm trying to cross-compile, and I need to also cross-compile opencl. I'll close this thread, as it's not an actually an issue.
